# Generated by Django 5.2.8 on 2025-12-02 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keitaro_flow_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('campaign_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('action_options', models.JSONField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('state', models.CharField(max_length=100)),
                ('action_type', models.CharField(max_length=100)),
                ('action_payload', models.TextField(blank=True, null=True)),
                ('schema', models.TextField(blank=True, null=True)),
                ('collect_clicks', models.BooleanField(default=False)),
                ('filter_or', models.BooleanField(default=False)),
                ('weight', models.IntegerField(default=100)),
                ('offer_selection', models.CharField(max_length=100)),
                ('filters', models.JSONField(default=list)),
                ('triggers', models.JSONField(default=list)),
                ('landings', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keitaro_offer_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OfferFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share', models.IntegerField()),
                ('state', models.CharField(choices=[('pending_add', 'Подготовлен к отправке'), ('published', 'Опубликован'), ('pending_delete', 'Подготовлен к удалению'), ('deleted', 'Удален')], max_length=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='keitaro_wrapper.flow')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='keitaro_wrapper.offer')),
            ],
        ),
    ]
