# Generated by Django 5.2.8 on 2025-12-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keitaro_wrapper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerflow',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
