# Generated by Django 5.2.8 on 2025-12-02 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keitaro_wrapper', '0002_offerflow_is_pinned'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='offerflow',
            unique_together={('flow', 'offer')},
        ),
    ]
